### ISSUE TITLE
server started on port: undefined

### ISSUE THREAD

**Issue by k8p8sz** [rishikesh2003/Aglypto#1]
It seems running on windows but cant find the port as it states undefined.
"server started on port: undefined"

**Comment by rkeshs** [comment]
Sorry for not adding that part in the docs. You need to,
1. Create a .env file in the directory and add,
2. `PORT=8000` or which port you want the server to run.
3. The server will start on `localhost:8000`

**Comment by rkeshs** [comment]
If you still have issues, please follow up or I can close it! 🙂

**Comment by k8p8sz** [comment]
> Sorry for not adding that part in the docs. You need to,
> 
> 1. Create a .env file in the directory and add,
> 2. `PORT=8000` or which port you want the server to run.
> 3. The server will start on `localhost:8000`

Many thanks, it works now!

**Comment by rkeshs** [comment]
I am closing the issue! :)
